version: "3.9"
services:
  app:
    build: ./
    command: ./mongoGraph
    ports:
      - "8080:8080"
    depends_on:
      - dataBase

  dataBase:
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"